
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 200314Birthday



Logging:
  level:
    com.wms: debug


logging:
  level:
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate=DEBUG: